### ISSUE TITLE
GitHub Compliance Checklist

### ISSUE THREAD

**Issue by agomezvidal89** [gsbDBI/torch-choice#53]
***
This issue lists the items in our compliance checklist that need to be addressed for this repo.
Please establish a timeline for each item to ensure completion. **You should include this timeline in the issue within a week from today.** For guidelines, please review [this document](https://docs.google.com/document/d/17dmApuA2yOBu8GvUCfLubE-a5rGYbH6ZQUAvDNFSbgk/edit?usp=sharing) or message @agomezvidal89.

***

# General Comments

- [ ] Project goals, milestones, and timelines are recorded in the wiki.
- [ ] Each milestone has a corresponding issue listing the tasks to complete the milestone, often with links to other issues for specific tasks. 
- [ ] Milestones are also included in your progress report with a link to the issue.
- [ ] All files/notebooks you work on are committed 
- [ ] For materials created on other platforms, like Google Presentations, Docs, or Overleaf, copies of those are also committed to GitHub. 
- [ ] All issues have been reviewed and only active issues are currently open
- [ ] Additional items to consider

# Wiki Structure

### 1.1. Project description

- [ ] Project status
- [ ] The motivation for the project;
- [ ] A summary of the research design and
- [ ] A summary of the results

### 1.2. Important links

- [ ] Google Drive (link)
- [ ] Meeting Notes (link)
- [ ] Pre-analysis Plan (link)
- [ ] Overleaf (link)
- [ ] Working paper (link)

### 1.3. Deliverables (once available)

- [ ] Link to code for figures, tables, and final document
- [ ] Link to final figures, tables, and final document

#### Faculty Collaborators (if relevant)

- [ ] Name
- [ ] Email
- [ ] Affiliation
- [ ] Start date
- [ ] Project role

#### Lab Members

- [ ] Name (Project Lead)
- [ ] Start date

#### Other Collaborators (if relevant)

- [ ] Name
- [ ] Email
- [ ] Affiliation
- [ ] Start date
- [ ] Project role

#### Faculty Collaborators (if relevant)

- [ ] Name
- [ ] Email
- [ ] Affiliation
- [ ] Start date
- [ ] Project role

#### Lab Members

- [ ] Name (Project Lead)
- [ ] Start date
- [ ] End date

#### Other Collaborators (if relevant)

- [ ] Name
- [ ] Email
- [ ] Affiliation
- [ ] Start date
- [ ] Project role

### 1.6. Partner (if relevant)

- [ ] Partner name (website link)
- [ ] Other relevant links (link)
- [ ] Description of the partner with the following information:
- [ ] Organization type (e.g., for-profit, NGO, government)
- [ ] Organization mission
- [ ] Description of what the organization does

#### Contacts

- [ ] Name
- [ ] Email
- [ ] Role in Organization
- [ ] Date of Initial Contact

#### Relationship

- [ ] Frequency of meetings and how they are organized
- [ ] Important milestones in relationship
- [ ] Information relevant to a long-term relationship with Partner

### 1.7. Data Use Agreement (If there is no agreement, say “no agreement has been proposed or signed.”) 

- [ ] Agreement (link)
- [ ] Brief description of DUA
- [ ] Expiration date of DUA
- [ ] Data sharing restrictions 

### 1.8. Other Agreements (If there are no other agreements, like a Non-disclosure Agreement (NDA), say “no other agreement has been proposed or signed.”) 

- [ ] Agreement (link)
- [ ] Brief description of agreement
- [ ] Who should sign the agreement
- [ ] List of personnel who have signed the agreement
- [ ] Any expiration dates

### 1.9. IRB  (If no IRB is required, explain why it is not required (e.g., using existing, publicly available data).) 

- [ ] Protocol (link)
- [ ] Approval letter (link)
- [ ] Expiration Date

## 2. Goals/Milestones/Timeline Page
This page contains: 

- [ ] Last updated date
- [ ] Project Deliverables listed (e.g., academic paper, public report, tutorial)
- [ ] Each goal, milestone, and timeline follows the same format: 

> Goal [deadline]
> Milestone [deadline] issue (link)
>  …
> Milestone [deadline] issue (link)

- [ ] Each milestone and issue is properly linked

## 3. Research Design/Pre-Analysis Plan Page

This page includes a roadmap of the project:
- [ ] Data descriptives
- [ ]  Model
- [ ] Experimentation/Inference
- [ ] Relevant notebooks

If the project has a pre-analysis plan, this page also includes: 
- [ ] Analysis notebooks
- [ ] Pilot data
- [ ] Write up raw code
- [ ] Pdf copy submitted
- [ ] Where it has been posted

## 4. Key Decisions Page

- [ ] Page follows the suggested structure
- [ ] All critical decisions up to date have been included on this page

## 5. Data Page
This page answers the following questions: 

### 5.1. Partner information (if applicable)
- [ ] Contact within our partner that gave us the original file 
- [ ] Name
- [ ] Email address

### 5.2. Raw data received from partner

- [ ] High-level description of how the partner pulled the data file (This will be context specific. For example, name or description of the database, whether they wrote code to join tables and create this dataset, etc.)

### 5.3. Original data file that we received from partner

- [ ] What it was (format)
- [ ] When we received it
- [ ] How we received it (e.g. File Transfer Protocol)
- [ ] Who among lab staff has access to it
- [ ] Where are the original data file and all subsequent files stored [be specific: include the file path in each case]

### 5.4. Raw data publicly available

- [ ] Date of the pull
- [ ] Who pulled it
- [ ] Code (if any) used to pull or download the raw data file 

### 5.5 Qualtrics surveys data 

- [ ] Name and the link to each Qualtrics project
- [ ] Who is the owner of the survey 
- [ ] Who else has access to it
- [ ] Link with folders to data files for easy access

### 5.6. Data management

- [ ] Confirmation that we have an unaltered file received from the partner and that we track derived data from raw data
- [ ] Who has access to the data files and how [include specifics, such as whether you had to receive a specific laptop or get permission to access certain servers, and how]
- [ ] Where the data analysis is carried out by whom [again, be specific!]
- [ ] Who among lab staff has access to all data stored?

### 5.7. Retention: Please detail all data policies agreed upon with the partner. 

- [ ] If raw data needs to be deleted, when, and by whom (lab members or partners)
- [ ] How long can files be preserved by partner; where they need to be stored; who is our person of contact for accessing them; what to do to avoid getting files deleted. 

## 6. Presentations Page

- [ ] Page follows suggested structure
- [ ] There is a clear indication of which files were used to create the presentations.
- [ ] Input for the presentation comes from a folder in GitHub that includes the presentation-quality figures.  
- [ ] If the figures are made in Excel or something else, those are committed.  
- [ ] There is a folder structure that makes identifying the input easy (e.g. it should be clear where the paper and presentation figures are saved in the directory structure, and it should be clear where the script that generates them is from the issue that includes the commit of the figures.)
- [ ] All past presentations and confirmed upcoming ones are listed in the wiki
